### ISSUE TITLE
Apparently you need a glottal stop in Slot 2 if there are multiple Slot 5 affixes

### ISSUE THREAD

**Issue by ghost** [ngoriyasjil/IthkuilGloss#37]
~~I tried to gloss the word "aẓplärlipšarsuömm", which has three slot 5 affixes (-rli, -pša, and -rsuö), which roughly translates to "the idea of hypothetical triangles tuned to F# that are 64th in a set by sequential physical arrangement" and the bot said there are unexpectedly many Slot 5 affixes. I then tried "aẓplärlipšamm" (4th in the set, removing the +60 affix -rsuö) and it still gave the same error. It was only on removing two affixes from the set (-pša and -rsuö) with the word "aẓplärlimm" that the bot managed to make a gloss.~~

Edit: apparently you need a Slot 2 glottal stop to indicate multiple Slot 5 affixes, even though the geminated Ca already tells you both that there are Slot 5 affixes and where they end... weird

**Comment by zsakowitz** [comment]
In Ithkuil, you need a glottal stop in Slot II to indicate that there are two or more Slot V affixes. See http://ithkuil.net/newithkuil_07_affixes.htm#:~:text=7.3%C2%A0%C2%A0%20Glottal%20Stop%20Requirements for more information. ![Screenshot 2023-08-20 at 7 00 18 AM](https://github.com/ngoriyasjil/IthkuilGloss/assets/65452710/8bf686f6-6f08-4515-bbad-f32fe39c96de)

**Comment by ghost** [comment]
Woops... idk why that's needed but it is
