### ISSUE TITLE
delete glosses with a message reaction

### ISSUE THREAD

**Issue by uakci** [ngoriyasjil/IthkuilGloss#6]
this one should be a quickie. [I'm still stuck working on the `sweep` branch so hold tight people]

@ngoriyasjil wanna assign this one to yourself?

**Comment by ngoriyasjil** [comment]
I'll take care of it. I'd like it to be a bit more robust to avoid 1) accidents 2) malice. A specific reaction by the author should do the trick. (Although I can already see a slight problem with determining the author, so perhaps just the specific reaction?)

**Comment by ngoriyasjil** [comment]
And donnnne.
